CREATE TABLE IF NOT EXISTS CUENTA_CONTABLE (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO_CONTABLE VARCHAR(30) NOT NULL,
  NOMBRE VARCHAR(150) NOT NULL,
  CLASE VARCHAR(20) NOT NULL,
  NATURALEZA_SALDO VARCHAR(15) NOT NULL,
  TIPO_CUENTA VARCHAR(15) NOT NULL,
  CUENTA_PADRE_ID INT NULL,
  NIVEL INT NOT NULL,
  PERMITE_MOVIMIENTOS TINYINT(1) NOT NULL DEFAULT 0,
  SALDO_ACTUAL DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_CUENTA_CONTABLE PRIMARY KEY (ID),
  CONSTRAINT UK_CUENTA_CONTABLE_CODIGO UNIQUE (CODIGO_CONTABLE),
  CONSTRAINT FK_CUENTA_CONTABLE_PADRE FOREIGN KEY (CUENTA_PADRE_ID) REFERENCES CUENTA_CONTABLE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_CUENTA_CONTABLE_CLASE CHECK (CLASE IN ('ACTIVO','PASIVO','PATRIMONIO','INGRESO','GASTO')),
  CONSTRAINT CK_CUENTA_CONTABLE_NAT CHECK (NATURALEZA_SALDO IN ('DEUDORA','ACREEDORA')),
  CONSTRAINT CK_CUENTA_CONTABLE_TIPO CHECK (TIPO_CUENTA IN ('ESTRUCTURAL','DETALLE')),
  CONSTRAINT CK_CUENTA_CONTABLE_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA')),
  CONSTRAINT CK_CUENTA_CONTABLE_MOV CHECK ((TIPO_CUENTA='DETALLE' AND PERMITE_MOVIMIENTOS=1) OR (TIPO_CUENTA='ESTRUCTURAL' AND PERMITE_MOVIMIENTOS=0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CUENTA_INSTITUCIONAL (
  ID INT AUTO_INCREMENT NOT NULL,
  CUENTA_CONTABLE_ID INT NOT NULL,
  CODIGO_FUNCIONAL VARCHAR(50) NOT NULL,
  NOMBRE VARCHAR(150) NOT NULL,
  TIPO_CUENTA VARCHAR(40) NOT NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_CUENTA_INSTITUCIONAL PRIMARY KEY (ID),
  CONSTRAINT UK_CUENTA_INST_CODIGO UNIQUE (CODIGO_FUNCIONAL),
  CONSTRAINT FK_CUENTA_INST_CONTABLE FOREIGN KEY (CUENTA_CONTABLE_ID) REFERENCES CUENTA_CONTABLE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_CUENTA_INST_TIPO CHECK (TIPO_CUENTA IN ('BANCO_CENTRAL','BOVEDA','IVA_RETENIDO','INGRESOS_COMISION','FONDOS_RESERVADOS','CUENTAS_CLIENTES')),
  CONSTRAINT CK_CUENTA_INST_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JORNADA_CONTABLE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  FECHA_CONTABLE DATE NOT NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ABIERTA',
  HORA_CORTE TIME NOT NULL DEFAULT '20:00:00',
  FECHA_APERTURA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_CIERRE DATETIME NULL,
  OBSERVACION VARCHAR(500) NULL,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_JORNADA_CONTABLE PRIMARY KEY (ID),
  CONSTRAINT UK_JORNADA_FECHA UNIQUE (FECHA_CONTABLE),
  CONSTRAINT CK_JORNADA_ESTADO CHECK (ESTADO IN ('ABIERTA','EN_CIERRE','CERRADA','BLOQUEADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ASIENTO_CONTABLE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_ASIENTO CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NOT NULL,
  TRANSACCION_UUID CHAR(36) NULL,
  CONTEXTO_ORIGEN VARCHAR(40) NOT NULL,
  TIPO_OPERACION VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(500) NOT NULL,
  FECHA_CONTABLE DATE NOT NULL,
  TIMESTAMP_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'REGISTRADO',
  REFERENCIA_EXTERNA VARCHAR(120) NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_ASIENTO_CONTABLE PRIMARY KEY (ID),
  CONSTRAINT UK_ASIENTO_UUID UNIQUE (UUID_ASIENTO),
  CONSTRAINT CK_ASIENTO_ESTADO CHECK (ESTADO IN ('BORRADOR','REGISTRADO','RECHAZADO','REVERSADO')),
  CONSTRAINT CK_ASIENTO_CONTEXTO CHECK (CONTEXTO_ORIGEN IN ('ACCOUNT','SWITCH','VENTANILLA','BANCA_WEB','EOD','CORE_INTERNO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS DETALLE_ASIENTO_CONTABLE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  ASIENTO_CONTABLE_ID BIGINT NOT NULL,
  CUENTA_CONTABLE_ID INT NOT NULL,
  TIPO_MOVIMIENTO VARCHAR(10) NOT NULL,
  MONTO DECIMAL(19,2) NOT NULL,
  REFERENCIA VARCHAR(200) NULL,
  ORDEN_LINEA INT NOT NULL,
  CONSTRAINT PK_DETALLE_ASIENTO PRIMARY KEY (ID),
  CONSTRAINT FK_DETALLE_ASIENTO FOREIGN KEY (ASIENTO_CONTABLE_ID) REFERENCES ASIENTO_CONTABLE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT FK_DETALLE_CUENTA_CONTABLE FOREIGN KEY (CUENTA_CONTABLE_ID) REFERENCES CUENTA_CONTABLE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_DETALLE_TIPO CHECK (TIPO_MOVIMIENTO IN ('DEBITO','CREDITO')),
  CONSTRAINT CK_DETALLE_MONTO CHECK (MONTO > 0),
  CONSTRAINT UK_DETALLE_ORDEN UNIQUE (ASIENTO_CONTABLE_ID, ORDEN_LINEA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS PROCESO_EOD (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_EOD CHAR(36) NOT NULL,
  JORNADA_CONTABLE_ID BIGINT NOT NULL,
  FECHA_CONTABLE DATE NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'INICIADO',
  TOTAL_DEBITOS DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  TOTAL_CREDITOS DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  UUID_DOCUMENTO_REPORTE CHAR(36) NULL,
  MENSAJE_ERROR VARCHAR(1000) NULL,
  FECHA_INICIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_FIN DATETIME NULL,
  CONSTRAINT PK_PROCESO_EOD PRIMARY KEY (ID),
  CONSTRAINT UK_EOD_UUID UNIQUE (UUID_EOD),
  CONSTRAINT FK_EOD_JORNADA FOREIGN KEY (JORNADA_CONTABLE_ID) REFERENCES JORNADA_CONTABLE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_EOD_ESTADO CHECK (ESTADO IN ('INICIADO','EN_PROCESO','EXITOSO','FALLIDO','REVERSADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BALANCE_COMPROBACION (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_BALANCE CHAR(36) NOT NULL,
  PROCESO_EOD_ID BIGINT NOT NULL,
  FECHA_CONTABLE DATE NOT NULL,
  TOTAL_SALDO_DEUDOR DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  TOTAL_SALDO_ACREEDOR DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'GENERADO',
  FECHA_GENERACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UUID_DOCUMENTO_CSV CHAR(36) NULL,
  CONSTRAINT PK_BALANCE PRIMARY KEY (ID),
  CONSTRAINT UK_BALANCE_UUID UNIQUE (UUID_BALANCE),
  CONSTRAINT FK_BALANCE_EOD FOREIGN KEY (PROCESO_EOD_ID) REFERENCES PROCESO_EOD(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_BALANCE_ESTADO CHECK (ESTADO IN ('GENERADO','CUADRADO','DESCADRADO','ANULADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BALANCE_COMPROBACION_DETALLE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  BALANCE_COMPROBACION_ID BIGINT NOT NULL,
  CUENTA_CONTABLE_ID INT NOT NULL,
  CODIGO_CONTABLE VARCHAR(30) NOT NULL,
  NOMBRE_CUENTA VARCHAR(150) NOT NULL,
  SALDO_DEUDOR DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  SALDO_ACREEDOR DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  ORDEN_LINEA INT NOT NULL,
  CONSTRAINT PK_BALANCE_DETALLE PRIMARY KEY (ID),
  CONSTRAINT FK_BALANCE_DETALLE_BAL FOREIGN KEY (BALANCE_COMPROBACION_ID) REFERENCES BALANCE_COMPROBACION(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT FK_BALANCE_DETALLE_CTA FOREIGN KEY (CUENTA_CONTABLE_ID) REFERENCES CUENTA_CONTABLE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT UK_BALANCE_DETALLE_LINEA UNIQUE (BALANCE_COMPROBACION_ID, ORDEN_LINEA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS AUDITORIA_ACCOUNTING_EVENTO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  UUID_USUARIO CHAR(36) NULL,
  UUID_API_CLIENT CHAR(36) NULL,
  SCOPE_USADO VARCHAR(120) NULL,
  MODULO VARCHAR(60) NOT NULL,
  ACCION VARCHAR(80) NOT NULL,
  ENTIDAD VARCHAR(80) NOT NULL,
  ENTIDAD_ID VARCHAR(80) NULL,
  RESULTADO VARCHAR(15) NOT NULL,
  DETALLE_JSON JSON NULL,
  FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_AUDITORIA_ACCOUNTING PRIMARY KEY (ID),
  CONSTRAINT CK_AUDITORIA_ACCOUNTING_RESULTADO CHECK (RESULTADO IN ('OK','ERROR','DENEGADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS OUTBOX_EVENT (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_EVENTO CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  AGREGADO_TIPO VARCHAR(80) NOT NULL,
  AGREGADO_ID VARCHAR(80) NOT NULL,
  PAYLOAD_JSON JSON NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  INTENTOS INT NOT NULL DEFAULT 0,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_PUBLICACION DATETIME NULL,
  ERROR_ULTIMO VARCHAR(1000) NULL,
  CONSTRAINT PK_OUTBOX_ACCOUNTING PRIMARY KEY (ID),
  CONSTRAINT UK_OUTBOX_ACCOUNTING_UUID UNIQUE (UUID_EVENTO),
  CONSTRAINT CK_OUTBOX_ACCOUNTING_ESTADO CHECK (ESTADO IN ('PENDIENTE','PUBLICADO','ERROR','DESCARTADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
