INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS) VALUES
('1','ACTIVOS','ACTIVO','DEUDORA','ESTRUCTURAL',NULL,1,0),
('2','PASIVOS','PASIVO','ACREEDORA','ESTRUCTURAL',NULL,1,0),
('4','INGRESOS','INGRESO','ACREEDORA','ESTRUCTURAL',NULL,1,0);

INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS)
SELECT '1.1','DISPONIBILIDADES','ACTIVO','DEUDORA','ESTRUCTURAL', ID, 2, 0 FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='1';
INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS)
SELECT '2.1','OBLIGACIONES CON CLIENTES','PASIVO','ACREEDORA','ESTRUCTURAL', ID, 2, 0 FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='2';

INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS)
SELECT '1.1.0.01','BANCO CENTRAL / CAMARA','ACTIVO','DEUDORA','DETALLE', ID, 3, 1 FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='1.1';
INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS)
SELECT '1.1.0.02','BOVEDA / EFECTIVO EN CAJA','ACTIVO','DEUDORA','DETALLE', ID, 3, 1 FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='1.1';
INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS)
SELECT '2.1.0.01','CUENTAS CLIENTES','PASIVO','ACREEDORA','DETALLE', ID, 3, 1 FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='2.1';
INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS)
SELECT '2.2.0.01','IVA RETENIDO','PASIVO','ACREEDORA','DETALLE', ID, 2, 1 FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='2';
INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS)
SELECT '2.3.0.01','FONDOS RESERVADOS PAGOS MASIVOS','PASIVO','ACREEDORA','DETALLE', ID, 2, 1 FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='2';
INSERT IGNORE INTO CUENTA_CONTABLE (CODIGO_CONTABLE,NOMBRE,CLASE,NATURALEZA_SALDO,TIPO_CUENTA,CUENTA_PADRE_ID,NIVEL,PERMITE_MOVIMIENTOS)
SELECT '4.1.0.01','INGRESOS SERVICIOS MASIVOS','INGRESO','ACREEDORA','DETALLE', ID, 2, 1 FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='4';

INSERT IGNORE INTO CUENTA_INSTITUCIONAL (CUENTA_CONTABLE_ID,CODIGO_FUNCIONAL,NOMBRE,TIPO_CUENTA)
SELECT ID, 'BC_CAMARA', 'Banco Central / Camara', 'BANCO_CENTRAL' FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='1.1.0.01';
INSERT IGNORE INTO CUENTA_INSTITUCIONAL (CUENTA_CONTABLE_ID,CODIGO_FUNCIONAL,NOMBRE,TIPO_CUENTA)
SELECT ID, 'BOVEDA_CENTRAL', 'Boveda Central', 'BOVEDA' FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='1.1.0.02';
INSERT IGNORE INTO CUENTA_INSTITUCIONAL (CUENTA_CONTABLE_ID,CODIGO_FUNCIONAL,NOMBRE,TIPO_CUENTA)
SELECT ID, 'CLIENTES_PASIVO', 'Cuentas clientes', 'CUENTAS_CLIENTES' FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='2.1.0.01';
INSERT IGNORE INTO CUENTA_INSTITUCIONAL (CUENTA_CONTABLE_ID,CODIGO_FUNCIONAL,NOMBRE,TIPO_CUENTA)
SELECT ID, 'IVA_RETENIDO', 'IVA Retenido', 'IVA_RETENIDO' FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='2.2.0.01';
INSERT IGNORE INTO CUENTA_INSTITUCIONAL (CUENTA_CONTABLE_ID,CODIGO_FUNCIONAL,NOMBRE,TIPO_CUENTA)
SELECT ID, 'FONDOS_RESERVADOS_PM', 'Fondos Reservados Pagos Masivos', 'FONDOS_RESERVADOS' FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='2.3.0.01';
INSERT IGNORE INTO CUENTA_INSTITUCIONAL (CUENTA_CONTABLE_ID,CODIGO_FUNCIONAL,NOMBRE,TIPO_CUENTA)
SELECT ID, 'INGRESOS_SERVICIOS_MASIVOS', 'Ingresos Servicios Masivos', 'INGRESOS_COMISION' FROM CUENTA_CONTABLE WHERE CODIGO_CONTABLE='4.1.0.01';
